### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by Anamichel-leon** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Anamichel-leon#1]
[Mapa mental de la web 3.0-Ana Michel Leon Leon.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Anamichel-leon/files/14662315/Mapa.mental.de.la.web.3.0-Ana.Michel.Leon.Leon.pdf)

**Comment by luzm23** [comment]
Identificación del tema principal  :4
Contenidos / Conceptos:4
Organización y estructura:4
Formato:4
Difusión:4
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
